FROM carlonluca/qt-dev-base:jammy
ENTRYPOINT ["/bin/bash", "-l", "-c"]
WORKDIR /root

ARG TARGETARCH
ARG QTVER

COPY qt_export/Qt-amd64-$QTVER.tar.xz /root/
COPY qt_export/Qt-arm64-$QTVER.tar.xz /root/
COPY qt_export/Qt-android-$QTVER.tar.xz /root/

COPY builder/toolchain.cmake /root/

# Android
RUN export DEBIAN_FRONTEND=noninteractive \
 && export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 \
 && apt-get update \
 && apt-get install -y openjdk-11-jdk sdkmanager \
 && sdkmanager "platforms;android-31" "platform-tools" "build-tools;31.0.0" \
 && export ANDROID_SDK_ROOT=/opt/android-sdk \
 && sdkmanager "ndk;25.1.8937393" \
 && export ANDROID_NDK_ROOT=/opt/android-sdk/ndk/25.1.8937393 \
 && yes | sdkmanager --licenses

ENV ANDROID_NDK_ROOT=/opt/android-sdk/ndk/25.1.8937393

RUN \
    cd /opt && \
    tar xvfp /root/Qt-arm64-$QTVER.tar.xz && \
    rm /root/Qt-arm64-$QTVER.tar.xz

RUN \
    cd /opt && \
    if [ "$TARGETARCH" != "arm64" ]; then \
        tar xvfp /root/Qt-amd64-$QTVER.tar.xz; \
        rm /root/Qt-amd64-$QTVER.tar.xz; \
        tar xvfp /root/Qt-android-$QTVER.tar.xz; \
        rm /root/Qt-android-$QTVER.tar.xz; \
    fi

RUN \
    echo "/opt/Qt-$TARGETARCH-$QTVER/lib" >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf \
 && ldconfig

RUN \
    rm -f /root/Qt-amd64-$QTVER.tar.xz \
 && rm -f /root/Qt-arm64-$QTVER.tar.xz \
 && rm -f /root/Qt-android-$QTVER.tar.xz

RUN \
    apt-get -y autoremove \
 && apt-get -y autoclean \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/opt/Qt-$TARGETARCH-$QTVER/bin:/opt/Qt-$TARGETARCH-$QTVER/libexec"
ENV QT_HOST_PATH="/opt/Qt-$TARGETARCH-$QTVER/"
ENV QT_PLUGIN_PATH="/opt/Qt-$TARGETARCH-$QTVER/plugins"
