FROM carlonluca/qt-dev-base:noble-17-35-27.2.12479018
ENTRYPOINT ["/bin/bash", "-l", "-c"]
WORKDIR /root

ARG TARGETARCH
ARG QTVER

COPY qt_export/Qt-amd64-$QTVER.tar.xz /root/
COPY qt_export/Qt-arm64-$QTVER.tar.xz /root/
COPY qt_export/Qt-android-$QTVER.tar.xz /root/

COPY builder/toolchain.cmake /root/

RUN \
    mkdir -p /opt/qt/$QTVER && \
    cd /opt/qt/$QTVER && \
    tar xvfp /root/Qt-arm64-$QTVER.tar.xz && \
    rm /root/Qt-arm64-$QTVER.tar.xz

RUN \
    cd /opt/qt/$QTVER && \
    if [ "$TARGETARCH" != "arm64" ]; then \
        tar xvfp /root/Qt-amd64-$QTVER.tar.xz; \
        rm /root/Qt-amd64-$QTVER.tar.xz; \
        tar xvfp /root/Qt-android-$QTVER.tar.xz; \
        rm /root/Qt-android-$QTVER.tar.xz; \
    fi

RUN \
    if [ "$TARGETARCH" = "arm64" ]; then \
        echo "/opt/qt/$QTVER/gcc_64/lib" >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf; \
    elif [ "$TARGETARCH" = "amd64" ]; then \
        echo "/opt/qt/$QTVER/gcc_arm64/lib" >> /etc/ld.so.conf.d/aarch64-linux-gnu.conf; \
    fi \
 && ldconfig

RUN \
    rm -f /root/Qt-amd64-$QTVER.tar.xz \
 && rm -f /root/Qt-arm64-$QTVER.tar.xz \
 && rm -f /root/Qt-android-$QTVER.tar.xz

RUN \
    apt-get -y autoremove \
 && apt-get -y autoclean \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

RUN \
    if [ "$TARGETARCH" = "arm64" ]; then \
        ln -s /opt/qt/$QTVER/gcc_arm64 /opt/Qt-$TARGETARCH-$QTVER; \
    elif [ "$TARGETARCH" = "amd64" ]; then \
        ln -s /opt/qt/$QTVER/gcc_64 /opt/Qt-$TARGETARCH-$QTVER; \
    fi

ENV PATH="${PATH}:/opt/Qt-$TARGETARCH-$QTVER/bin:/opt/Qt-$TARGETARCH-$QTVER/libexec"
ENV QT_HOST_PATH="/opt/Qt-$TARGETARCH-$QTVER/"
ENV QT_PLUGIN_PATH="/opt/Qt-$TARGETARCH-$QTVER/plugins"
