FROM ubuntu:bionic

COPY sources.list_bionic /etc/apt/sources.list

RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    export CMAKE_VERSION="3.24.2" && \
    dpkg --add-architecture arm64 && \
    apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install build-essential && \
    apt install -y --no-install-recommends curl ca-certificates software-properties-common xz-utils && \
    apt-get -y install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu python-pip freeglut3-dev:arm64 gdb git iputils-ping \
    libgl1-mesa-dev:arm64 libglu1-mesa-dev:arm64 libjpeg-dev:arm64 libmysqlclient-dev:arm64 \
    libnss3-dev:arm64 libopus-dev:arm64 libpng-dev:arm64 libsqlite3-dev:arm64 libssl-dev:arm64 \
    libx11-xcb-dev:arm64 libxcb-xinerama0-dev:arm64 libxcb-xkb-dev:arm64 libxcb1-dev:arm64 \
    libxcursor-dev:arm64 libxi-dev:arm64 libxml2-dev:arm64 libxrender-dev:arm64 libxslt-dev:arm64 \
    lzip mesa-common-dev:arm64 nano perl python3 valgrind wget zlib1g-dev:arm64 '^libxcb.*-dev:arm64' \
    libxkbcommon-dev:arm64 libxkbcommon-x11-dev:arm64 wget libwayland-dev:arm64 flex bison gperf \
    libicu-dev:arm64 libxslt-dev:arm64 ruby libxcursor-dev:arm64 libxcomposite-dev:arm64 \
    libxdamage-dev:arm64 libxrandr-dev:arm64 libxtst-dev:arm64 libxss-dev:arm64 libdbus-1-dev:arm64 \
    libevent-dev:arm64 libfontconfig1-dev:arm64 libcap-dev:arm64 libpulse-dev:arm64 libudev-dev:arm64 \
    libpci-dev:arm64 libnss3-dev:arm64 libasound2-dev:arm64 libegl1-mesa-dev:arm64 gperf bison nodejs \
    libasound2-dev:arm64 libgstreamer1.0-dev:arm64 libgstreamer-plugins-base1.0-dev:arm64 \
    libgstreamer-plugins-good1.0-dev:arm64 libnspr4-dev:arm64 libcups2-dev:arm64 \
    libmng-dev:arm64 libwebp-dev:arm64 libxcb-xinput-dev:arm64 libwebpmux3:arm64 libvpx-dev:arm64 \
    libavformat-dev:arm64 libavcodec-dev:arm64 libavutil-dev:arm64 libswresample-dev:arm64 libswscale-dev:arm64 libavdevice-dev:arm64 libzstd-dev:arm64 \
    libpcre2-dev:arm64 libxshmfence-dev:arm64 libxkbfile-dev:arm64 libbluetooth-dev:arm64 \
    libsctp-dev:arm64 libsnappy-dev:arm64 libharfbuzz-dev:arm64 libminizip-dev:arm64 \
    libb2-dev:arm64 libva-dev:arm64 \
    \
    g++-aarch64-linux-gnu gcc-aarch64-linux-gnu ninja-build && \
    set -xe && \
    curl -Lo install-cmake.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh && \
    chmod +x install-cmake.sh && \
    ./install-cmake.sh --skip-license --prefix=/usr/local && \
    rm -fv install-cmake.sh && \
    \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt install -y --no-install-recommends gcc-11 g++-11 cpp-11 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
                         --slave /usr/bin/gcov gcov /usr/bin/gcov-11 \
                         --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 \
                         --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11 && \
    update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 110 && \
    \
    apt-get -y install freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libjpeg-dev libmysqlclient-dev \
    libnss3-dev libopus-dev libpng-dev libsqlite3-dev libssl-dev \
    libx11-xcb-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb1-dev \
    libxcursor-dev libxi-dev libxml2-dev libxrender-dev libxslt-dev mesa-common-dev \
    zlib1g-dev '^libxcb.*-dev' libxkbcommon-dev libxkbcommon-x11-dev libwayland-dev \
    libicu-dev libxslt-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev \
    libxss-dev libdbus-1-dev libevent-dev libfontconfig1-dev libcap-dev libpulse-dev libudev-dev \
    libpci-dev libnss3-dev libasound2-dev libegl1-mesa-dev libasound2-dev libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libnspr4-dev libcups2-dev libcupsimage2-dev liborc-0.4-dev \
    libavformat-dev libavcodec-dev libavutil-dev libswresample-dev libswscale-dev libavdevice-dev \
    libmng-dev libwebp-dev libxcb-xinput-dev libwebpmux3 libvpx-dev zstd libzstd-dev \
    libpcre2-dev python3 python3-html5lib libxshmfence-dev libxkbfile-dev libbluetooth-dev \
    libsctp-dev libsnappy-dev libharfbuzz-dev libminizip-dev libb2-dev libva-dev libtiff-dev     && \
    \
    apt-get -y autoremove && \
    apt-get -y autoclean && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

COPY toolchain.cmake /root/toolchain.cmake
