FROM carlonluca/appimage-builder:jammy

WORKDIR /root

RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install \
        build-essential cmake freeglut3-dev gdb iputils-ping libgl1-mesa-dev \
        libglu1-mesa-dev libjpeg-dev libmysqlclient-dev libnss3-dev libopus-dev \
        libpng-dev libsqlite3-dev libssl-dev libx11-xcb-dev libxcb-xinerama0-dev \
        libxcb-xkb-dev libxcb1-dev libxcursor-dev libxi-dev libxml2-dev libxrender-dev \
        libxslt-dev lzip mesa-common-dev nano perl python3 valgrind wget zlib1g-dev \
        '^libxcb.*-dev' libxkbcommon-dev libxkbcommon-x11-dev wget libwayland-dev ninja-build && \
    apt-get -y install flex bison gperf libicu-dev libxslt-dev ruby && \
    apt-get -y install libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev \
        libxtst-dev libxss-dev libdbus-1-dev libevent-dev libfontconfig1-dev \
        libcap-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev \
        libegl1-mesa-dev gperf bison nodejs && \
    apt-get -y install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev libcups2-dev \
        libavformat58 libavcodec58 libavutil56 libswresample3 libswscale5 libavdevice58 \
        libmng2 libwebp7 libxcb-xinput0 libwebpmux3 libvpx7 libzstd1 libpcre2-16-0 libxshmfence1 libclang1 \
        libllvm14 libxkbfile1 libbluetooth3 libsctp1 libsnappy1v5 libmd4c0 libmd4c-html0 libharfbuzz0b libminizip1 libb2-1 libva2 && \
    apt-get install -y protobuf-compiler

RUN export DEBIAN_FRONTEND=noninteractive \
 && export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
 && apt-get update \
 && apt-get -y install git git-lfs ccache \
 && apt-get install -y openjdk-17-jdk sdkmanager

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV ANDROID_SDK_ROOT=/opt/android-sdk

# Android
RUN sdkmanager "platforms;android-34" "platform-tools" "build-tools;34.0.0" \
 && export ANDROID_SDK_ROOT=/opt/android-sdk \
 && sdkmanager "ndk;26.1.10909125" \
 && export ANDROID_NDK_ROOT=/opt/android-sdk/ndk/26.1.10909125 \
 && yes | sdkmanager --licenses

ENV ANDROID_NDK_ROOT=/opt/android-sdk/ndk/26.1.10909125
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN \
    apt-get -y autoremove \
 && apt-get -y autoclean \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*
